// Copyright (c) Microsoft Corporation.
// Licensed under the Apache 2.0.

/** Filename of the GitHub Actions deployment workflow generated by the agent. */
export const PIPELINE_WORKFLOW_FILENAME = 'deploy-to-aks.yml';

/** Path to the Copilot setup-steps workflow pushed by the setup PR. */
export const COPILOT_SETUP_STEPS_PATH = '.github/workflows/copilot-setup-steps.yml';

/** Path to the containerization agent config pushed by the setup PR. */
export const AGENT_CONFIG_PATH = '.github/agents/containerization.agent.md';

/**
 * GitHub bot usernames that may author PRs created by the Copilot Coding Agent.
 * Stored lowercase — always compare with `.toLowerCase()`.
 */
export const COPILOT_BOT_USERS = new Set(['copilot-swe-agent[bot]', 'copilot[bot]', 'copilot']);

/** Default image tag mandated in agent instructions. */
export const DEFAULT_IMAGE_TAG = '1.0';

/** Custom DOM event used to open the pipeline drawer from a separate React tree. */
export const OPEN_CONFIGURE_PIPELINE_EVENT = 'open-configure-pipeline';

/** Prefix for localStorage keys that store pipeline state per repo. */
export const STORAGE_KEY_PREFIX = 'aks-desktop:pipeline-state:';

/** Schema version for serialized pipeline state. Bump when the shape changes. */
export const SCHEMA_VERSION = 1;

/** Version of the containerization-assist-mcp used in agent setup steps. */
export const CONTAINERIZATION_MCP_VERSION = '1.3.2';

/** Default polling interval for GitHub API checks (5 seconds). */
export const POLLING_INTERVAL_MS = 5_000;

/** App installation check interval (3 seconds). */
export const APP_INSTALL_CHECK_INTERVAL_MS = 3_000;

/** PR polling: 5s x 720 = 1 hour max. */
export const PR_POLLING_MAX_POLLS = 720;

/** Workflow polling: 5s x 360 = 30 minutes max. */
export const WORKFLOW_POLLING_MAX_POLLS = 360;

/** Agent PR discovery: 5s x 120 = 10 minutes max. */
export const AGENT_DISCOVERY_MAX_POLLS = 120;
