name: Build aks-desktop (Windows)

on:
  schedule:
    # Runs every day at 1:00 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      aks_plugin_branch:
        description: 'Branch to build aks-plugin'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install golang
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.24.*'

      - name: Setup nodejs
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20.x

      - name: Checkout this repository with submodules
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.inputs.aks_plugin_branch }}
          submodules: recursive

      - name: Setup AKS desktop and Build Headlamp (Windows)
        run: npm run build:win-ci
        shell: bash

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: aks-desktop-win
          path: headlamp/app/dist/aks-desktop*.*
